nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: http://github.com/tarunbatra

projects_url: http://github.com/tarunbatra

customize:
    gravatar:
        email: tarun.batra00@gmail.com
    logo:
        enabled: true
        width: 50
        height: 50
        url: # /images/logo.png
        gravatar: true
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
      github: https://github.com/tarunbatra
      stack-overflow: https://stackoverflow.com/users/story/2751596
      twitter: https://twitter.com/tarunbatra
      linkedin: https://www.linkedin.com/in/tarunbatra00
    post_count: 5
    highlight: rainbow

# RSS
rss:

# Plugins
plugins:
    disqus_shortname: tarunbatra # Disqus Comments Shortname
    google_analytics: UA-47797084-2 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
